name: Issue Notification

on:
  schedule:
    - cron: '0 9 * * *'  # 毎日午前9時にチェック
  issues:
    types: [opened, edited]
  workflow_dispatch:  # 手動トリガー

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Get Project Card Information
        run: |
          # Project IDを設定
          project_id="YOUR_PROJECT_ID"
          
          # プロジェクトカードの取得
          card_details=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/projects/columns/cards?project_id=$project_id")

          # 必要な開始日と終了日の抽出
          start_date=$(echo "$card_details" | jq -r '.[0].created_at')  # ここで開始日を取得
          end_date=$(echo "$card_details" | jq -r '.[0].due_date')  # 終了日をカスタムフィールドとして取得
          
          # 取得した開始日と終了日を表示
          echo "Start date: $start_date"
          echo "End date: $end_date"

      - name: Send progress check notification to Discord
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
            "content": "進捗状況を確認してください: Project Card - 開始日: $start_date, 終了日: $end_date"
          }' ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Post progress comment to issue
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{
            "body": "進捗状況: [進捗内容] - 終了予定日を確認しましたか？"
          }' \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"
